### ISSUE TITLE
Entity

### ISSUE THREAD

**Issue by pulss** [petrleocompel/hass-wattrouter-mx#1]
Dobrý den,
do Ha jsem nainstaloval podle navodu, uspesne jsem se prihlasil, ale u zarizeni v HA nevidim zadne entity.
Prosím poradíte?
Děkuji

**Comment by petrleocompel** [comment]
Záleží na typu zařízení. Trochu více informací by neuškodilo.

**Comment by pulss** [comment]
Omlouvám se, mam Watrouter MX, jedná se mi mi o formatovany kod do configuration.yaml. Dekuji

**Comment by petrleocompel** [comment]
Omlouvám se. Nerozumím. Integrace se přidává v UI. Vyplní se formulář a začne fungovat. 

https://www.home-assistant.io/getting-started/integration/

**Comment by kucerazdenek** [comment]
mám Wattrouter MX a chovalo se mi to úplně stejně, pokud jsem v konfiguraci integrace zadal pouze IP adresu. Když jsem zadal http://<ip_adresa>, tak to začalo fungovat

**Comment by kucerazdenek** [comment]
> Ano jak ukazuje "placeholder" pole. V `Address` je nutno zadat `Adresu` aka včetně `scheme`. Viz ukázka "placeholderu" `http://ip`. Plný příklad `http://192.168.0.10`

jj, souhlas. Já odpovídal předřečníkovi @pulss který tam neviděl žádné entity, akorát jsem zapomněl dát reply :)

**Comment by petrleocompel** [comment]
Bohužel nebylo poskytnuto více informací. Aktuálně neeviduji žádné chyby. Primárně mi sloužilo ovládání jednotlivých relé. 
Nyní integraci skoro nepoužívám. Žádná zajímavá data pro mě z ní nevyčtu. Pokud by někdo chtěl může zadat novou "issue" a můžeme prodiskutovat. Vytáhnout data by šlo.
